learning_rate: [0.001, 0.005, 0.01, 0.05, 0.1]
batch_size: 50
weight_decay: 1e-3
lr_scheduler: 0
learning_rate_decay: 0.9998
num_rounds: 1000
num_epochs: [5]
clip_grad: 10
proportion: 0.2
early_stop: 250
train_holdout: 0.2
local_test: True
no_log_console: True
log_file: True